name: Build Marketplace
description: Sets up Java, Maven Cache and builds the Marketplace.
inputs:
    SKIP_TESTS:
      description: 'Skip Maven Tests'
      default: 'false'
      required: true
    WORKING_DIRECTORY:
      description: 'Working directory for the steps'
      required: true
      default: '.'

runs:
  using: composite
  steps:
  - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
    with:
      java-version: 21
      distribution: temurin
      cache: maven

  - name: Get submodule SHA
    shell: bash
    id: get-submodule-sha
    run: echo "SUBMODULE_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    working-directory: ${{ inputs.WORKING_DIRECTORY }}/api.adoptium.net

  - name: Cache api.adoptium.net packages
    uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
    id: cache-api
    with:
      path: ~/.m2/repository/net/adoptium/api
      key: maven-repo-${{ steps.get-submodule-sha.outputs.SUBMODULE_SHA }}
      restore-keys: maven-repo-${{ steps.get-submodule-sha.outputs.SUBMODULE_SHA }}

  - name: Build api
    shell: bash
    if: steps.cache-api.outputs.cache-hit != 'true'
    working-directory: ${{ inputs.WORKING_DIRECTORY }}/api.adoptium.net
    run: ./mvnw --batch-mode clean install -Padoptium -DskipTests=${{ inputs.SKIP_TESTS }}

  - name: Build marketplace
    shell: bash
    working-directory: ${{ inputs.WORKING_DIRECTORY }}
    run: ./mvnw --batch-mode clean install -DskipTests=${{ inputs.SKIP_TESTS }}
