name: Build Marketplace
description: Sets up Java, Maven Cache and builds the Marketplace.
inputs:
    RUN_TESTS:
      description: 'Run Maven Tests (deprecated, use SKIP_TESTS instead)'
      default: 'true'
      required: false
    SKIP_TESTS:
      description: 'Skip Maven Tests'
      default: 'false'
      required: false
    WORKING_DIRECTORY:
      description: 'Working directory for the steps'
      required: true
      default: '.'

runs:
  using: composite
  steps:
  - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
    with:
      java-version: 21
      distribution: temurin
      cache: maven

  - name: Get submodule SHA
    shell: bash
    id: get-submodule-sha
    run: echo "SUBMODULE_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    working-directory: ${{ inputs.WORKING_DIRECTORY }}/api.adoptium.net

  - name: Cache api.adoptium.net packages
    uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
    id: cache-api
    with:
      path: ~/.m2/repository/net/adoptium/api
      key: maven-repo-${{ steps.get-submodule-sha.outputs.SUBMODULE_SHA }}
      restore-keys: maven-repo-${{ steps.get-submodule-sha.outputs.SUBMODULE_SHA }}

  - name: Build api
    shell: bash
    if: steps.cache-api.outputs.cache-hit != 'true'
    working-directory: ${{ inputs.WORKING_DIRECTORY }}/api.adoptium.net
    run: ./mvnw --batch-mode clean install -Padoptium -DskipTests=${{ inputs.SKIP_TESTS || inputs.RUN_TESTS == false }}

  - name: Build marketplace
    shell: bash
    working-directory: ${{ inputs.WORKING_DIRECTORY }}
    run: ./mvnw --batch-mode clean install -DskipTests=${{ inputs.SKIP_TESTS || inputs.RUN_TESTS == false }}
